spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sport?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver

  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 1000
        min-idle: 100
#        max-wait: 100ms

server:
  servlet:
    context-path: /sport



mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml
